apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ambienttv.fullname" . }}-secrets
  labels:
    {{- include "ambienttv.labels" . | nindent 4 }}
type: Opaque
stringData:
  APP_SECRET: {{ .Values.secrets.appSecret | quote }}
  ADMIN_PASSWORD_HASH: {{ .Values.secrets.adminPasswordHash | quote }}
  PEXELS_API_KEY: {{ .Values.secrets.pexelsApiKey | quote }}
  PIXABAY_API_KEY: {{ .Values.secrets.pixabayApiKey | quote }}
  YOUTUBE_API_KEY: {{ .Values.secrets.youtubeApiKey | quote }}
  COVERR_API_KEY: {{ .Values.secrets.coverrApiKey | quote }}
